---
name: CI

on:
  workflow_dispatch:

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        experimental: [false]
        nox-session: [""]
        include:
          - python-version: 3.10-dev
            experimental: true
            nox-session: test-3.10

    runs-on: ubuntu-latest
    name: test-${{ matrix.python-version }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install nox
          pip install pytest
      - name: Install Thundra Python Agent
        uses: thundra-io/thundra-foresight-python-action@action-experiment
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }} 
      - name: Run Tests
        shell: bash
        run: .ci/run-nox.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          NOX_SESSION: ${{ matrix.nox-session }}
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_DEBUG_ENABLE: true
